# Generated by Django 2.2.2 on 2019-06-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20190620_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='imdb_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='links',
            name='movie_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='links',
            name='tmdb_id',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
