# Generated by Django 2.2.2 on 2019-06-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20190620_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='title',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='tags',
            name='tag',
            field=models.TextField(blank=True, default='', max_length=256),
        ),
    ]
